# Generated by Django 5.2.7 on 2026-01-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupylekcyjne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_grupy', models.CharField(max_length=255)),
                ('liczba_godzin_w_grupie', models.IntegerField()),
                ('rozmieszczenie', models.TextField(default='BRAK')),
            ],
            options={
                'db_table': 'grupylekcyjne',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Klasa',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nazwa', models.CharField(blank=True, max_length=255, null=True)),
                ('rok', models.IntegerField(blank=True, null=True)),
                ('ilosc_osob', models.IntegerField(blank=True, null=True)),
                ('ograniczenia_dni', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'klasa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Klasywgrupach',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'klasywgrupach',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nauczyciel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie_nazwisko', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'nauczyciel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ograniczenia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('od', models.IntegerField(blank=True, db_column='od_', null=True)),
                ('do', models.IntegerField(blank=True, db_column='do_', null=True)),
                ('dzien_tygodnia', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'ograniczenia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OgraniczeniaKlas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dzien_tygodnia', models.CharField(max_length=20)),
                ('od', models.IntegerField(db_column='od_')),
                ('do', models.IntegerField(db_column='do_')),
            ],
            options={
                'db_table': 'ograniczenia_klas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlanLekcji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dzien_tygodnia', models.CharField(blank=True, max_length=20, null=True)),
                ('godzina_lekcyjna', models.IntegerField(blank=True, null=True)),
                ('sala', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'plan_lekcji',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Przedmioty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_przedmiotu', models.CharField(blank=True, max_length=255, null=True)),
                ('skrot', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'przedmioty',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WymaganiaPrzedmiotowe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liczba_godzin', models.IntegerField(blank=True, null=True)),
                ('rozmieszczenie', models.TextField(default='BRAK')),
            ],
            options={
                'db_table': 'wymagania_przedmiotowe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatusGeneratora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ_zadania', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('OCZEKIWANIE', 'Oczekiwanie'), ('PRACA', 'Przetwarzanie... (to może potrwać do 10 min)'), ('SUKCES', 'Zakończono pomyślnie'), ('BLAD', 'Wystąpił błąd')], default='OCZEKIWANIE', max_length=20)),
                ('wiadomosc', models.TextField(blank=True, null=True)),
                ('data_rozpoczecia', models.DateTimeField(auto_now_add=True)),
                ('data_zakonczenia', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
